version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started
    
   Globals:
    Function:
    Runtime: java coretto
    Timeout: 180
       Environment:
      Variables:
        Var1: "Hello"

Resources:
  CICDLambda:
    Handler: handler.CICDLambda
    Type: AWS::Serverless::Function
    Properties:
      Role: Lambda_role
      Runtime: Java 8 on Amazon Linux 1
      MemorySize: 3 GB
      AutoPublishAlias: !Ref Stage
      DeploymentPreference:
       Type: AllAtOnce
      Environment:
        Variables:
          MESSAGE: "Hello From Lambda"
          TEST: "Demo"
    
  post_build:
    commands:
    - echo Build completed
    - mvn package
    - mv target/CICDLambda-0.0.1-SNAPSHOT.jar CICDLambda-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - CICDLambda-0.0.1-SNAPSHOT.jar
   #- .ebextensions/**/*
