Globals:
  Function:
    Runtime: java coretto
    Timeout: 180
    Handler: com.lambda1.LambdaDemo1::handleRequest
    Environment:
      Variables:
        Var1: "Hello"

Resources:
  CICDLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: lambda_role
      Runtime: Java 8 on Amazon Linux 1
      MemorySize: 3 GB
      AutoPublishAlias: !Ref Stage
      DeploymentPreference:
       Type: AllAtOnce
      Environment:
        Variables:
          MESSAGE: "Hello From Lambda"
          TEST: "Demo"
      