 Function:
   Runtime: java coretto
    Timeout: 240
       Environment:
      Variables:
        Var1: "Hello"

Resources:
  CICDLambda:
    Handler: com.cicddemo.CICDLambda::handleRequest
    Type: AWS::Serverless::Function
    Properties:
      Role: Lambda_role
      Runtime: Java 8 on Amazon Linux 1
      MemorySize: 3 GB
      AutoPublishAlias: !Ref Stage
      DeploymentPreference:
       Type: AllAtOnce
      Environment:
        Variables:
          MESSAGE: "Hello From Lambda"
          TEST: "Demo"
